# Generated by Django 3.2.3 on 2021-05-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
